config/routes.rb
Sppl::Application.routes.draw do
  
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end
  
  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  resources :user_sessions
  
  resources :users
 
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "players#index"
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :matches

  def name
    return "Season ##{self.ordinal}"
  end

  def to_s
    name
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < InheritedResources::Base
  actions :create, :destroy, :edit, :index, :new, :show, :update
  before_filter :require_user

  def new_match
    @season = Season.find(params[:id])
    @match = @season.matches.build
  end

end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th><%= f.label :ordinal %></th>
      <td><%= f.text_field :ordinal %></td>
    </tr>
    <tr>
      <th><%= f.label :start_year %></th>
      <td><%= f.text_field :start_year %></td>
    </tr>
    <tr>
      <th><%= f.label :stop_year %></th>
      <td><%= f.text_field :stop_year %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/_index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Start Year</th>
    <th>Stop Year</th>
    <th># of Matches</th>
<% if changes_allowed? %>
    <th class="actions">Actions</th>
<% end %>
  </tr>
<% @seasons.each do |season| %>
  <tr>
    <td><%= link_to "#{season}", season %></td>
    <td class="numeric"><%= season.start_year %></td>
    <td class="numeric"><%= season.stop_year %></td>
    <td class="numeric"><%= season.matches.count %></td>
<% if changes_allowed? %>
    <td class="actions">
      <%= link_to "Change", edit_season_path(season) %>&nbsp;/
      <%= link_to "Remove", season, :confirm => "Are you sure?", :method => :delete %>
    </td>
<% end %>
  </tr>
<% end %>
</table>
<p/>
<% if changes_allowed? %>
<%= link_to "Add a New Season", new_season_path %>
<% end %>

app/views/seasons/_show.html.erb
<table>
  <tr>
    <th>Name:</th>
    <td>Season <%= @season.ordinal %></td>
  </tr>
  <tr>
  <th><%= link_to("Matches:", matches_path, :season_id => @season.id) -%></th>
    <td>
      <% for match in @season.matches %>
        <%= link_to "#{match}", match_path(match) %><br/>
      <% end %>
      <% if @season.matches.empty? %><i>None</i><% end %>
    </td>
  </tr>
<% if changes_allowed? %>
  <tr>
    <th class="actions">Actions</th>
    <td class="actions"><%= link_to "Add a Match", :action => 'new_match', :id => @season.id %></td>
  </tr>
<% end %>
</table>

app/views/seasons/new_match.html.erb
<h3>New Match for <%= @season.name %></h3>
<%= render :partial => "matches/form", :locals => {:match => @match} %>