config/routes.rb
Sppl::Application.routes.draw do
  
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end
  
  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  resources :user_sessions
  
  resources :users
 
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "players#index"
end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :match
  
  has_many :results, :dependent => :destroy, :order => "place"
  has_many :players, :through => :results, :order => "place"

  accepts_nested_attributes_for :results, :allow_destroy => true

  def <(another_game)
    if self.match.match_date == another_game.match.match_date 
      return self.ordinal < another_game.ordinal
    end
    self.match.match_date < another_game.match.match_date
  end

  def <=>(another_game)
    if self.match.match_date == another_game.match.match_date 
      return self.ordinal <=> another_game.ordinal
    end
    self.match.match_date <=> another_game.match.match_date
  end

  def name
    return "Game ##{ordinal}"
  end

  def to_s
    "#{ordinal}"
  end

end

app/controllers/games_controller.rb
class GamesController < InheritedResources::Base

  actions :destroy, :show
  before_filter :require_user
 
  def choose_players
    @game = Game.find(params[:id])
    @players = Player.active.sorted_by_first_name
    render :action => :new
  end
  
  def create
    @game = Game.new(params[:game])
    @game.players = Player.find(params[:player_ids]) if params[:player_ids]
    if @game.save
      flash[:notice] = "Game was successfully created!"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def index
    @page_title = "Showing All Games"
    @season = (params[:season_id].nil?) ? Season.find(:last) : Season.find(params["season_id"])
    @matches = @season.matches
  end

  def new
    @game = Game.new
    @players = Player.active.sorted_by_first_name
  end

  def update
    @game = Game.find(params[:id])
    @game.players = Player.find(params[:player_ids]) if params[:player_ids]
    if @game.update_attributes(params[:game])
      flash[:notice] = "Game was successfully updated!"
      redirect_to :action => :show, :id => @game
    else
      render :action => :edit
    end
  end

end

app/views/games/_form.html.erb
<div id="Editor">
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this Game from being saved:</h2>
      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th>Game #</th>
      <td><%= f.text_field :ordinal %></td>
    </tr>
    <tr>
      <th><%= f.label :match %></th>
      <td><%= f.collection_select(:match_id, Match.all, :id, :match_date)%></td>
    </tr>
      <th>Players</th>
      <td>
        <table>
        <% @players.each do |player| %>
          <tr>
            <td><%= check_box_tag "player_ids[]", "#{player.id}", @game.players.include?(player) -%></td>
            <td><%= player %></td>
          </tr>
        <% end %>
      </table>
    </td>
  </table>
  <p/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/games/_index.html.erb
<table>
  <tr>
    <th>Match</th>
    <th>Game #</th>
    <th>Player Count</th>
<% if changes_allowed? %>
    <th class="actions">Actions</th>
<% end %>
  </tr>
<%
  @matches.each do |match|
    if !match.games.empty?
%>
  <tr>
    <td rowspan="<%= match.games.count %>"><%= link_to "#{match}", match %></td>
<%
      match.games.sort.each { |game| 
%>
    <td class="numeric"><%= link_to "#{game.ordinal}", game %></td>
    <td class="numeric"><%= game.players.count %></td>
<% if changes_allowed? %>
    <td class="actions">
      <%= link_to "Change", edit_game_path(game) %>&nbsp;/
      <%= link_to "Remove", game, :confirm => "Are you sure?", :method => :delete %>
    </td>
<% end %>
  </tr>
<%
      }
    else
%>
  <tr>
    <td><%= link_to "#{match}", match %></td>
    <td colspan="4">No Games</td>
  </tr>
<%
    end 
  end
%>
</table>
<p/>
<% if changes_allowed? %>
<%= link_to 'Add a New Game', new_game_path %>
<% end %>

app/views/games/_show.html.erb
<div id="ViewerCompressed">
  <table cellpadding="5" cellspacing="3">
    <tr>
      <th align="right">Match:</th>
      <td><%= link_to @game.match.match_date, match_path(@game.match) %></td>
    </tr>
    <tr>
      <th align="right">Game #</th>
      <td><%= @game.ordinal %></td>
    </tr>
    <tr>
      <th align="right">Players:</th>
      <td>
        <% if @game.players.empty? %>
        <i>None</i>
      <% else %>
        <table cellpadding="3" cellspacing="3">
          <% @game.results.each do |result| %>
            <tr>
              <td><%= result.place %>.</td>
              <td><%= link_to "#{result.player}", player_path(result.player) %></td>
              <td>(<%= result.points %>)</td>
            </tr>
          <% end %>
        </table>
        <% end %>
      </td>
    </tr>
<% if changes_allowed? %>
    <tr>
      <th>Actions</th>
      <td><%= link_to "Choose Players", :action => :choose_players, :id => @game.id %></td>
    </tr>
<% end %>
  </table>
</div>

app/views/games/edit.html.erb
<div id="ViewerCompressed">
  <%= form_for(@game, :action => :update, :id => @game.id) do |f| %>
    <table>
      <tr>
        <th align="right">Match:</th>
        <td><%= link_to @game.match.match_date, match_path(@game.match) %></td>
      </tr>
      <tr>
        <th align="right">Game #</th>
        <td><%= @game.ordinal %></td>
      </tr>
      <tr>
        <th align="right">Results:</th>
        <td>
          <% if @game.players.empty? %>
            <i>None</i>
          <% else %>
            <table>
              <% f.fields_for :results do |result_form| %>
                <tr>
                  <td><%= "#{result_form.object.place}." -%></td>
                  <td><%= result_form.collection_select :player_id, @game.players, :id, :to_s, :selected => result_form.object.player.id -%></td>
                </tr>
              <% end %>
            </table>
          <% end %>
        </td>
      </tr>
      <% if changes_allowed? %>
        <tr>
          <th>Actions</th>
          <td><%= link_to "Choose Players", :action => :choose_players, :id => @game.id %></td>
        </tr>
      <% end %>
    </table>
    <%= f.submit "Save" if changes_allowed? %>
  <% end %>
</div>
<%= link_to 'Show', resource %> |
<%= link_to 'View All', {:controller => params[:controller], :action => :index} %>