config/routes.rb
Sppl::Application.routes.draw do
  
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end
  
  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  resources :user_sessions
  
  resources :users
 
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "players#index"
end

app/models/player.rb
class Player < ActiveRecord::Base

  has_many :results, :dependent => :restrict
  has_many :games, :through => :results, :order => "place"

  scope :active, where(1 == 1)
  
  def <=>(another_player)
    self.total_points <=> another_player.total_points
  end

  def self.sorted_by_first_name
    order('first_name, last_name')
  end
  
  def full_name
    return "#{self.first_name} #{self.last_name}"
  end

  def non_scoring_results(season_id)
    self.season_results(season_id) - self.scoring_results(season_id)
  end

  def scoring_results(season_id)
    ary = self.season_results(season_id).sort {|x, y| y.points <=> x.points}
    ary[0..5]
  end

  def season_games(season_id)
    self.season_results(season_id).collect {|result| result.game}
  end

  def season_results(season_id)
    self.results.select {|result| result.game.match.season_id == season_id}
  end

  def season_total_points(season_id)
    return 0 if self.season_results(season_id).nil? 
    p = self.scoring_results(season_id).inject(0) {|sum, each| sum + each.points}
    p.round(2)
  end

  def to_s
    full_name
  end

  def total_points
    self.season_total_points(Season.find(:last).id)
  end

end

app/controllers/players_controller.rb
class PlayersController < InheritedResources::Base

  actions :create, :destroy, :edit, :new, :show, :update
 
  def index
    @page_title = "All Players"
    self.set_season
    @players = Player.all.sort.reverse
  end

  def move
    if ["move_lower", "move_higher"].include?(params[:method]) and params[:game_player_id] =~ /^\d+$/
      gp = Result.find(params[:game_player_id])
      gp.send(params[:method]) unless gp.nil?
    end
    redirect_to :controller => :games, :action => :show, :id => gp.game.id
  end

  def set_season
    @season = (params[:season_id].nil?) ? Season.find(:last) : Season.find(params["season_id"])
  end

  def show
    self.set_season
    show! { @page_title = "Showing a Player" }
  end

end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this Player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th>Player #</th>
      <td><%= "#{@player.id}" %></td>
    </tr>
    <tr>
      <th><%= f.label :first_name %></th>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <th><%= f.label :last_name %></th>
      <td><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <th><%= f.label :email %></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th><%= f.label :phone %></th>
      <td><%= f.text_field :phone %></td>
    </tr>
  </table>
  <p/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_index.html.erb
<table>
  <tr>
    <th>Place</th>
    <th>Player</th>
    <th>Total Points</th>
    <th>Games Played</th>
    <% if changes_allowed? %>
      <th class="actions">Actions</th>
    <% end %>
  </tr>
  <%
    i = 1
    @players.each do |player|
      if player.season_games(@season.id).count > 0
    %>
    <tr>
      <td><%= i %></td>
      <td><%= link_to("#{player.full_name}", player) %></td>
      <td class="numeric"><%= player.season_total_points(@season.id) %></td>
      <td class="numeric"><%= player.season_games(@season.id).count %></td>
      <% if changes_allowed? %>
        <td class="actions">
          <%= link_to "Change", edit_player_path(player) %>&nbsp;/
          <%= link_to "Remove", player, :confirm => "Are you sure?", :method => :delete %>
        </td>
      <% end %>
    </tr>
    <%
      i += 1
    end
  end 
%>
</table>
<p/>
  <% if changes_allowed? %>
    <%= link_to "Add a New Player", new_player_path %>
  <% end %>

app/views/players/_show.html.erb
<h4>Details</h4>
<table>
  <tr>
    <th>Player</th>
    <td><%= @player.full_name %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= @player.email %></td>
  </tr>
  <tr>
    <th>Phone</th>
    <td><%= @player.phone %></td>
  </tr>
</table>
<p/>
<h4>Games Played</h4>
<% if @player.season_games(@season.id).empty? %>
<i>None</i>
<% else %>
<h5>Scoring</h5>
<table>
  <tr>
    <th>Match</th>
    <th>Game</th>
    <th>Place</th>
    <th>Points</th>
  </tr>
<%   for result in @player.scoring_results(@season.id) %>
  <tr>
    <td><%= link_to "#{result.game.match}", match_path(result.game.match) %></td>
    <td class="numeric"><%= link_to "#{result.game.ordinal}", game_path(result.game) %></td>
    <td class="numeric"><%= result.place %></td>
    <td class="numeric"><%= result.points %></td>
  </tr>
<%   end %>
</table>

<h5>Non-Scoring</h5>
<table>
  <tr>
    <th>Match</th>
    <th>Game</th>
    <th>Place</th>
    <th>Points</th>
  </tr>
<%   for result in @player.non_scoring_results(@season.id) %>
  <tr>
    <td><%= link_to "#{result.game.match}", match_path(result.game.match) %></td>
    <td class="numeric"><%= link_to "#{result.game.ordinal}", game_path(result.game) %></td>
    <td class="numeric"><%= result.place %></td>
    <td class="numeric"><%= result.points %></td>
  </tr>
<%   end %>
</table>
<% end %>
<p/>