config/routes.rb
Sppl::Application.routes.draw do
  
  resources :games do
    member do
      get :choose_players
    end
  end

  resources :game_players

  resources :matches do
    member do
      get :new_game
    end
  end
  
  resources :players do
    member do
      get :move
    end
  end

  resources :seasons do
    member do
      get :new_match
    end
  end

  resources :user_sessions
  
  resources :users
 
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "players#index"
end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :season
  has_many :games

  def to_s
    "#{self.match_date}"
  end

end

app/controllers/matches_controller.rb
class MatchesController < InheritedResources::Base

  actions :create, :destroy, :edit, :new, :show, :update
  before_filter :require_user

  def index
    @season = (params[:season_id].nil?) ? Season.find(:last) : Season.find(params["season_id"])
    @matches = @season.matches
  end

  def new_game
    @match = Match.find(params[:id])
    @game = @match.games.build
    @players = Player.all.sort {|a, b| a.full_name <=> b.full_name}
  end

end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this Match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <th><%= f.label :match_date %></th>
      <td><%= f.text_field :match_date %></td>
    </tr>
    <tr>
      <th><%= f.label :season %></th>
      <td><%= f.collection_select(:season_id, Season.all, :id, :name)%></td>
    </tr>
  </table>
  <p/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/_index.html.erb
<table>
  <tr>
    <th>Season</th>
    <th>Match</th>
<% if changes_allowed? %>
    <th class="actions">Actions</th>
  </tr>
<% end %>
<%
  if !@matches.empty?
%>
  <tr>
  <td rowspan="<%= @matches.count %>"><%= link_to @season, season_path(@season.id) -%></td>
<%
      @matches.each { |match| 
%>
    <td><%= link_to "#{match}", match %></td>
<% if changes_allowed? %>
    <td class="actions">
      <%= link_to "Change", edit_match_path(match) %>&nbsp;/
      <%= link_to "Remove", match, :confirm => "Are you sure?", :method => :delete %>
    </td>
<% end %>
  </tr>
<%
      }
    else
%>
  <tr>
    <td><%= @season %></td>
    <td colspan="4">No Matches</td>
  </tr>
<%
  end
%>
</table>
<p/>
<% if changes_allowed? %>
<%= link_to "Add a New Match", new_match_path %>
<% end %>

app/views/matches/_show.html.erb
<table border="1" cellpadding="5" cellspacing="3">
  <tr>
    <th align="right">Date:</th>
    <td><%= @match.match_date %></td>
  </tr>
  <tr>
    <th align="right">Season:</th>
    <td><%= link_to @match.season.name, season_path(@match.season) %></td>
  </tr>
  <tr>
    <th align="right">Games:</th>
    <td>
      <% for game in @match.games %>
        <%= link_to "#{game}", game_path(game) %><br/>
      <% end %>
      <% if @match.games.empty? %><i>None</i><% end %>
    </td>
  </tr>
<% if changes_allowed? %>
  <tr>
    <th>Actions</th>
    <td><%= link_to "Add a Game", :action => 'new_game', :id => @match.id %></td>
  </tr>
<% end %>
</table>

app/views/matches/new_game.html.erb
<h3>New Game for <%= @match %></h3>
<%= render :partial => "games/form", :locals => {:game => @game} %>